# URL HTTP API lấy từ dòng "Forwarding HTTP traffic from..." của Serveo
server.http.url=https://fd79cd8c41638aa3-42-118-25-182.serveousercontent.com

# Cấu hình kết nối Realtime Socket cố định qua cổng 6969 công cộng
server.socket.host=serveo.net
server.socket.port=6969