# Database configuration
db.url=jdbc:mysql://root:xQocNoyDrzXAvHViQhaVmzdwPgnZSyoZ@kodama.proxy.rlwy.net:11971/railway
db.user=root
db.password=xQocNoyDrzXAvHViQhaVmzdwPgnZSyoZ

# Server configuration
server.http.port=8000
server.socket.port=6969