# Cau hinh ket noi toi Server tren Railway
server.socket.host=kodama.proxy.rlwy.net
server.socket.port=13556

# Cau hinh URL goi http
server.http.url=https://auctionsystem-production-7bbb.up.railway.app