name: Java CI Automation

on:
  push:
    branches: [ master, tranvandung ]
  pull_request:
    branches: [ master, tranvandung ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    # MySQL Service chạy trên Linux để phục vụ quá trình test

    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: 'maven'

      - name: Build and Verify with JaCoCo
        run: mvn clean verify
        env:
          DATABASE_SECRET_KEY: ${{ secrets.APP_DB_CONN }}
          DB_URL: ${{ secrets.RAILWAY_DB_URL }}
          DB_USER: root
          DB_PASSWORD: ${{ secrets.RAILWAY_DB_PASSWORD }}

      - name: Upload JaCoCo Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-${{ matrix.os }}
          path: "**/target/site/jacoco/"

      - name: Automate Continuous Delivery (GitHub Release)
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && matrix.os == 'ubuntu-latest'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Production Release Build v1.0.${{ github.run_number }}
          body: |
            🎉 Hệ thống CD tự động phát hành phiên bản mới!
            - Trạng thái: Build & Kiểm thử thành công.
            - Mã định danh tự động: #${{ github.run_number }}
          files: |
            server/target/*.jar
            client/target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-docker:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Server Docker Image (CD Part 2)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: ghcr.io/tranvandung25020080/auction_system/auction-server:latest

  # chay tren may ao window de dong goi file exe
  build-client-windows-exe:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          # Nếu có distribution: 'temurin' thì giữ nguyên

      - name: Build Fat JAR with Maven
        run: mvn clean package -DskipTests

      - name: Lọc file sạch để chuẩn bị đóng gói
        run: |
          mkdir jpackage_input
          copy client\target\client-1.0-SNAPSHOT-jar-with-dependencies.jar jpackage_input\

      - name: Kích hoạt jpackage tạo bản cài đặt EXE
        run: jpackage --type exe --input jpackage_input --dest release_output --name AuctionClient --main-jar client-1.0-SNAPSHOT-jar-with-dependencies.jar --main-class com.auction.client.main.MainApplication --win-shortcut --win-dir-chooser

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          # Trỏ đường dẫn lấy file exe từ thư mục output
          files: release_output/AuctionClient-1.0.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}